import { useMaterialUIController } from "context";

function T(key) {
  const [controller] = useMaterialUIController();

  const langs = {
    en: {
      slider: "Slider",
      action: "Action",
      CampaginesView: "Campagines View",
      Campagines: "Campagines",

      language: "Language",
      SidenavColors: "Sidenav Colors",
      SidenavTypes: "Sidenav Types",
      SidenavTypesOptions: "Sidenav Types Options",

      White: "White",
      Dark: "Dark",
      Transparent: "Transparent",
      mode: "Light / dark Mode",
      app_name: "Winit Dashboard",
      app_config: "Choose ui Options",
      title: "Title",
      users: "Users",
      user: "User",

      products: "Products",
      product: "Product",
      main: "Main",
      lists: "Lists",
      useful: "Useful",
      dashboard: "Dashboard",
      orders: "Orders",

      categories: "Categories",
      addCategories: "Add Categories",
      AddNewCategoury: "Add New Categoury",
      editeCategories: "Edite Categories",

      search: "Search",
      delivery: "Delivery",
      stats: "statictis",
      noti: "Notifications",
      profile: "Profile",
      logout: "Logout",
      seeAll: "See All",

      days: "Days",
      week: "Week",
      month: "Month",
      Months: "Months",
      email: "E-Mail",
      age: "Age",
      action: "Action",
      view: "View",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      active: "Active",
      passive: "Passive",
      code: "Code",
      category: "Category",
      price: "Price",

      rate: "Rate",
      address: "Address",
      country: "Country",
      phone: "Phone",

      addNewUser: "add New User",
      admin: "Administrator",
      privileges: "Privileges",

      editeProd: "Edite Products",

      catDelete: "Category Will Deleted",
      catDeleted: "Category Deleted Successfuly",
      catDeletedError: "Error in  Deleting Category",
      cantReturn: "You Can't undo changes",
      catStatus: "Category will be activated/deactivate ",
      catStatusDone: "Category activated/deactivate Successfuly",
      catStatusError: "Error in activated/deactivate Category ",
      catAdded: "Category added/edited Successfuly",
      catAddedError: "Error in added/edited Category",

      prodDelete: "Product Will Deleted",
      prodDeleted: "Product Deleted Successfuly",
      prodDeletedError: "Error in  Deleting Product",
      prodStatus: "Product will be activated/deactivate ",
      prodStatusDone: "Product activated/deactivate Successfuly",
      prodStatusError: "Error in activated/deactivate Product  ",
      prodCatRequire: "Product name ,Category and Price Can't be empty",
      prodAdded: "Product added/edited Successfuly",
      prodAddedError: "Error in added/edited Product",

      userDelete: "User Will Deleted",
      userDeleted: "User Deleted Successfuly",
      userDeletedError: "Error in  Deleting User",
      userStatus: "User will be activated/deactivate ",
      userStatusDone: "User activated/deactivate Successfuly",
      userStatusError: "Error in activated/deactivate User  ",
      userAdded: "User added/edited Successfuly",
      userAddedError: "Error in added/edited User",
      categoryOfProduct: "Category",
      ProductDetails: "Product Details",
      ImageDetails: "Image Details",
      PriceDetails: "Price Details",
      inStock: "inStock",
      ordersView: "View Orders",
      orders: "Orders",

      productsView: "View Products",
      superAdmin: "Super Administrator",
    },
    ar: {
      action: "اجراء",
      CampaginesView: "عرض المسابقات",
      Campagines: "مسابقات",
      productsView: "عرض المنتجات",
      ordersView: "عرض الطلبات",
      orders: "الطلبات",
      language: "اللغة",
      SidenavColors: "الوان شريط التنقل",
      SidenavTypes: "انواع الوان شريط التنقل",
      SidenavTypesOptions: "اختار بين الانواع المختلفة",

      White: "ابيض",
      Dark: "غامق",
      Transparent: "شفاف",
      mode: "طبيعي / ليلي",
      app_name: "لوحة تحكم Winit",
      app_config: "اختار خصائص الواجهة",
      title: "عنوان",
      users: "المستخدمين",
      user: "مستخدم",

      products: "المنتجات",
      product: "منتج",
      main: "الرئيسية",
      lists: "القوائم",
      useful: "إضافية",
      dashboard: "لوحة التحكم",
      orders: "الطلبات",

      categories: "الفئات",
      addCategories: "اضافة تصنيف جديد",
      AddNewCategoury: "اضافة تصنيف جديد",
      editeCategories: "تعديل  التصنيف  ",

      search: "بحث",
      delivery: "التوصيل",
      stats: "الإحصائيات",
      noti: "إشعارات",
      profile: "الملف الشخصى",
      logout: "تسجيل خروج",
      seeAll: "عرض الكل",

      days: "أيام",
      week: "أسبوع",
      month: "شهر",
      Months: "شهور",
      email: "بريد إلكترونى",
      age: "سن",
      action: "إجراء",
      view: "عرض",
      delete: "حذف",
      slider: "عارض الصور",

      edit: "تعديل",
      add: "إضافة",
      active: "نشط",
      passive: "سلبى",
      code: "كود",
      category: "فئة",
      price: "سعر",

      rate: "التقييم",
      address: "العنوان",
      country: "الدولة",
      phone: "رقم الهاتف",

      addNewUser: "إضافة مستخدم جديد",
      admin: "مدير نظام",
      privileges: "الصلاحيات",

      editeProd: "تعديل المنتج",
      catDelete: "سيتم حذف التصنيف",
      catDeleted: "تم حذف التصنيف بنجاح",
      catDeletedError: "خطا في حذف التصنيف",
      cantReturn: "لن تستطيع اعادتها",
      catStatus: "سيتم تعطيل / تفعيل التصنيف ",
      catStatusDone: "تم  تعطيل / تفعيل التصنيف بنجاح",
      catStatusError: "خطا في  تعطيل / تفعيل التصنيف  ",
      catAdded: "تم اضافة/تعديل التصنيف بنجاح",
      catAddedError: "خطا في حذف  ضافة/تعديل التصنيف",

      prodDelete: "سيتم حذف المنتج",
      prodDeleted: "تم حذف المنتج",
      prodDeletedError: "خطا في حذف المنتج",
      prodStatus: "سيتم تعطيل / تفعيل المنتج ",
      prodStatusDone: "تم  تعطيل / تفعيل المنتج بنجاح",
      prodStatusError: "خطا في  تعطيل / تفعيل المنتج  ",
      prodCatRequire: "اسم المنتج والتصنيف والسعر لا يجب ان يكونوا فارغين",
      prodAdded: "تم اضافة/تعديل المنتج بنجاح",
      prodAddedError: "خطا في حذف  ضافة/تعديل المنتج",

      userDelete: "سيتم حذف المستخدم",
      userDeleted: "تم حذف المستخدم",
      userDeletedError: "خطا في حذف المستخدم",
      userStatus: "سيتم تعطيل / تفعيل المستخدم ",
      userStatusDone: "تم  تعطيل / تفعيل المستخدم بنجاح",
      userStatusError: "خطا في  تعطيل / تفعيل المستخدم  ",
      userAdded: "تم اضافة/تعديل المستخدم بنجاح",
      userAddedError: "خطا في حذف  ضافة/تعديل المستخدم",
      categoryOfProduct: "فئة الصنف",
      ProductDetails: "تفاصيل المنتج",
      ImageDetails: "صورة المنتج",
      PriceDetails: "تفاصيل السعر",
      inStock: "فى المتجر",

      superAdmin: "مشرف",
    },
  };
  let value = controller.direction === "rtl" ? langs.ar[key] : langs.en[key];
  return value ?? key;
}

export default T;
